# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false

matrix:
  include:
    - name: "Backend: TensorFlow | Implementation: Keras"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "Backend: Theano | Implementation: Keras"
      env:
        - KERAS_BACKEND="theano"
        - THEANO_FLAGS=optimizer=fast_compile
        - TENSORFLOW_VERSION="default"
    - name: "Backend: TensorFlow | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "Backend: TensorFlow Eager | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 1.12"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.12.0"
    - name: "Backend: TensorFlow | Implementation: TensorFlow 2.0.0a0"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="2.0.0-alpha0"
    - name: "Backend: Tensorflow | Implementation: TensorFlow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "Backend: Tensorflow Eager | Implementation: Tensorflow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
  allow_failures:
    - name: "Backend: Tensorflow | Implementation: TensorFlow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "Backend: Tensorflow Eager | Implementation: Tensorflow Nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "Backend: TensorFlow Eager | Implementation: TensorFlow"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
        
cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"))'
  - R -e 'tensorflow::tf_config()'
