# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false

matrix:
  include:
    - name: "TensorFlow (Keras)"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "Theano (Keras)"
      env:
        - KERAS_BACKEND="theano"
        - THEANO_FLAGS=optimizer=fast_compile
        - TENSORFLOW_VERSION="default"
    - name: "TensorFlow (TensorFlow)"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
    - name: "TensorFlow (TensorFlow Eager)"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (TensorFlow 1.12)"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="1.12.0"
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "nighly/eager"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (TensorFlow 2.0.0a0)"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="2.0.0-alpha0"
  allow_failures:
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "nighly/eager"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (TensorFlow 2.0.0a0)"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_VERSION="2.0.0-alpha0"
        
cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"))'
  - R -e 'tensorflow::tf_config()'
